services:
  db:
    image: mysql:8.0
    container_name: planner_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: planner_pro
      MYSQL_USER: planner_user
      MYSQL_PASSWORD: planner_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:7-alpine
    container_name: planner_cache
    restart: always
    ports:
      - '6379:6379'

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: planner_backend
    restart: always
    ports:
      - '3002:3001'
    environment:
      DATABASE_URL: mysql://planner_user:planner_password@db:3306/planner_pro
      REDIS_HOST: cache
      REDIS_PORT: 6379
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/home/node/app/backend
      - /home/node/app/backend/node_modules
      - /home/node/app/node_modules
    depends_on:
      - db
      - cache

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: planner_frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      VITE_API_URL: http://localhost:3002
    volumes:
      - ./frontend:/home/node/app/frontend
      - /home/node/app/frontend/node_modules
      - /home/node/app/node_modules
    depends_on:
      - backend


volumes:
  mysql_data:
